"""
Fidoo7 Driver - Expense Management API

Python driver for Fidoo expense management and prepaid card system.

Features:
- User management (create, read, update, deactivate)
- Prepaid card operations (view balance, load/unload funds)
- Transaction tracking (card, cash, account transactions)
- Expense management and reporting
- Travel request and report management
- Configuration settings (cost centers, projects, VAT, etc.)
- Rate limiting with automatic retry (6,000 requests/day)
- Cursor-based pagination
- Comprehensive error handling

Installation:
    pip install fidoo7-driver

Quick Start:
    from fidoo_driver import Fidoo7Driver

    # Load from environment
    client = Fidoo7Driver.from_env()

    # Or explicit credentials
    client = Fidoo7Driver(
        base_url="https://api.fidoo.com/v2/",
        api_key="your_api_key_here"
    )

    # Discover available endpoints
    objects = client.list_objects()
    print(objects)

    # Read data
    users = client.read("user/get-users", limit=50)
    print(f"Found {len(users)} users")

    # Cleanup
    client.close()

Environment Variables:
    FIDOO_API_KEY: API key (required)
    FIDOO_API_URL: API base URL (optional, default: production)
    FIDOO_TIMEOUT: Request timeout in seconds (optional)
    FIDOO_MAX_RETRIES: Max retry attempts (optional)
    FIDOO_DEBUG: Enable debug mode "true"/"false" (optional)
"""

__version__ = "1.0.0"
__author__ = "Generated by Claude Code"
__license__ = "MIT"

from .base import BaseDriver, DriverCapabilities, PaginationStyle
from .client import Fidoo7Driver
from .exceptions import (
    AuthenticationError,
    ConnectionError,
    DriverError,
    FieldNotFoundError,
    ObjectNotFoundError,
    QuerySyntaxError,
    RateLimitError,
    TimeoutError,
    ValidationError,
)

__all__ = [
    "Fidoo7Driver",
    "BaseDriver",
    "DriverCapabilities",
    "PaginationStyle",
    "DriverError",
    "AuthenticationError",
    "ConnectionError",
    "ObjectNotFoundError",
    "FieldNotFoundError",
    "QuerySyntaxError",
    "RateLimitError",
    "ValidationError",
    "TimeoutError",
]
